[build.environment]
  NODE_VERSION = "18"

[build]
  publish = ".vitepress/dist"
  command = "pnpm run build"

[[redirects]]
  from = "/deployment/"
  to = "/deployment/index.html"
  status = 200

[[redirects]]
  from = "/examples/"
  to = "/examples/index.html"
  status = 200

[[redirects]]
  from = "/frameworks/"
  to = "/frameworks/index.html"
  status = 200

[[redirects]]
  from = "/guide/"
  to = "/guide/index.html"
  status = 200

[[redirects]]
  from = "/workbox/"
  to = "/workbox/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
